server:
  port: 8080
  servlet:
    context-path: /gbabler

spring:
  profiles:
    active: ${PROFILE:dev}
  jpa:
    database: postgresql
    show-sql: false
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres