spring:
  jpa:
    database: postgresql
    show-sql: false
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/goals
    platform: postgres
    driverClassName: org.postgresql.Driver